version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    ports:
    - 8080:8080
    container_name: jenkins
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
    - 6379:6379
    container_name: redis
  
  