version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    ports:
    - 8080:8080
    container_name: jenkins
    volumes:
    - ~/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
  logstash:
    image: logstash:8.5.3
    restart: unless-stopped
    ports:
    - 3179:3179
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
    - 6379:6379
    container_name: redis
  
  